### ISSUE TITLE
404 on Preview

### ISSUE THREAD

**Issue by marexx** [bitstarr/grav-plugin-draft-preview#1]
I don't get it working.
draft-preview.yaml:
enabled: true
route: whybrand.com/preview

because it's in an subdirectory

but i always get a 404 error.

Marek

**Comment by bitstarr** [comment]
I will try to reproduce it, gimme some time.

**Comment by marexx** [comment]
thnx. i'm using [Grav] v1.7.37.1

**Comment by bitstarr** [comment]
```yaml
 route: preview
 ```
Setting the config to default will work now (see above). The preview page was created fine, but the button in admin linked to the wrong URL.

**Comment by marexx** [comment]
thnx, is working
